2024-05-14 21:13:27 | INFO | controller | args: Namespace(host='localhost', port=21001, dispatch_method='shortest_queue', ssl=False)
2024-05-14 21:13:27 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m67701[0m]
2024-05-14 21:13:27 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2024-05-14 21:13:27 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2024-05-14 21:13:27 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://localhost:21001[0m (Press CTRL+C to quit)
2024-05-14 21:13:46 | ERROR | stderr | [32mINFO[0m:     Shutting down
2024-05-14 21:13:46 | ERROR | stderr | [32mINFO[0m:     Waiting for application shutdown.
2024-05-14 21:13:46 | ERROR | stderr | [32mINFO[0m:     Application shutdown complete.
2024-05-14 21:13:46 | ERROR | stderr | [32mINFO[0m:     Finished server process [[36m67701[0m]
2024-05-14 21:13:46 | ERROR | stderr | Traceback (most recent call last):
2024-05-14 21:13:46 | ERROR | stderr |   File "/home/yyang/anaconda3/envs/matcha_new/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2024-05-14 21:13:46 | ERROR | stderr |     return _run_code(code, main_globals, None,
2024-05-14 21:13:46 | ERROR | stderr |   File "/home/yyang/anaconda3/envs/matcha_new/lib/python3.9/runpy.py", line 87, in _run_code
2024-05-14 21:13:46 | ERROR | stderr |     exec(code, run_globals)
2024-05-14 21:13:46 | ERROR | stderr |   File "/home/yyang/anaconda3/envs/matcha_new/lib/python3.9/site-packages/fastchat/serve/controller.py", line 389, in <module>
2024-05-14 21:13:46 | ERROR | stderr |     uvicorn.run(app, host=args.host, port=args.port, log_level="info")
2024-05-14 21:13:46 | ERROR | stderr |   File "/home/yyang/anaconda3/envs/matcha_new/lib/python3.9/site-packages/uvicorn/main.py", line 575, in run
2024-05-14 21:13:46 | ERROR | stderr |     server.run()
2024-05-14 21:13:46 | ERROR | stderr |   File "/home/yyang/anaconda3/envs/matcha_new/lib/python3.9/site-packages/uvicorn/server.py", line 65, in run
2024-05-14 21:13:46 | ERROR | stderr |     return asyncio.run(self.serve(sockets=sockets))
2024-05-14 21:13:46 | ERROR | stderr |   File "/home/yyang/anaconda3/envs/matcha_new/lib/python3.9/asyncio/runners.py", line 44, in run
2024-05-14 21:13:46 | ERROR | stderr |     return loop.run_until_complete(main)
2024-05-14 21:13:46 | ERROR | stderr |   File "uvloop/loop.pyx", line 1511, in uvloop.loop.Loop.run_until_complete
2024-05-14 21:13:46 | ERROR | stderr |   File "uvloop/loop.pyx", line 1504, in uvloop.loop.Loop.run_until_complete
2024-05-14 21:13:46 | ERROR | stderr |   File "uvloop/loop.pyx", line 1377, in uvloop.loop.Loop.run_forever
2024-05-14 21:13:46 | ERROR | stderr |   File "uvloop/loop.pyx", line 555, in uvloop.loop.Loop._run
2024-05-14 21:13:46 | ERROR | stderr |   File "uvloop/loop.pyx", line 474, in uvloop.loop.Loop._on_idle
2024-05-14 21:13:46 | ERROR | stderr |   File "uvloop/cbhandles.pyx", line 83, in uvloop.loop.Handle._run
2024-05-14 21:13:46 | ERROR | stderr |   File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
2024-05-14 21:13:46 | ERROR | stderr |   File "/home/yyang/anaconda3/envs/matcha_new/lib/python3.9/site-packages/uvicorn/server.py", line 69, in serve
2024-05-14 21:13:46 | ERROR | stderr |     await self._serve(sockets)
2024-05-14 21:13:46 | ERROR | stderr |   File "/home/yyang/anaconda3/envs/matcha_new/lib/python3.9/contextlib.py", line 124, in __exit__
2024-05-14 21:13:46 | ERROR | stderr |     next(self.gen)
2024-05-14 21:13:46 | ERROR | stderr |   File "/home/yyang/anaconda3/envs/matcha_new/lib/python3.9/site-packages/uvicorn/server.py", line 328, in capture_signals
2024-05-14 21:13:46 | ERROR | stderr |     signal.raise_signal(captured_signal)
2024-05-14 21:13:46 | ERROR | stderr | KeyboardInterrupt
2024-05-14 21:13:49 | ERROR | stderr | Exception ignored in: <module 'threading' from '/home/yyang/anaconda3/envs/matcha_new/lib/python3.9/threading.py'>
2024-05-14 21:13:49 | ERROR | stderr | Traceback (most recent call last):
2024-05-14 21:13:49 | ERROR | stderr |   File "/home/yyang/anaconda3/envs/matcha_new/lib/python3.9/threading.py", line 1424, in _shutdown
2024-05-14 21:13:49 | ERROR | stderr |     lock.acquire()
2024-05-14 21:13:49 | ERROR | stderr | KeyboardInterrupt:
2024-05-14 21:13:53 | INFO | controller | args: Namespace(host='localhost', port=21001, dispatch_method='shortest_queue', ssl=False)
2024-05-14 21:13:53 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m67731[0m]
2024-05-14 21:13:53 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2024-05-14 21:13:53 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2024-05-14 21:13:53 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://localhost:21001[0m (Press CTRL+C to quit)
2024-05-14 21:14:18 | INFO | stdout | [32mINFO[0m:     127.0.0.1:39426 - "[1mGET / HTTP/1.1[0m" [31m404 Not Found[0m
2024-05-14 21:14:32 | ERROR | stderr | [32mINFO[0m:     Shutting down
2024-05-14 21:14:32 | ERROR | stderr | [32mINFO[0m:     Waiting for application shutdown.
2024-05-14 21:14:32 | ERROR | stderr | [32mINFO[0m:     Application shutdown complete.
2024-05-14 21:14:32 | ERROR | stderr | [32mINFO[0m:     Finished server process [[36m67731[0m]
2024-05-14 21:14:32 | ERROR | stderr | Traceback (most recent call last):
2024-05-14 21:14:32 | ERROR | stderr |   File "/home/yyang/anaconda3/envs/matcha_new/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2024-05-14 21:14:32 | ERROR | stderr |     return _run_code(code, main_globals, None,
2024-05-14 21:14:32 | ERROR | stderr |   File "/home/yyang/anaconda3/envs/matcha_new/lib/python3.9/runpy.py", line 87, in _run_code
2024-05-14 21:14:32 | ERROR | stderr |     exec(code, run_globals)
2024-05-14 21:14:32 | ERROR | stderr |   File "/home/yyang/anaconda3/envs/matcha_new/lib/python3.9/site-packages/fastchat/serve/controller.py", line 389, in <module>
2024-05-14 21:14:32 | ERROR | stderr |     uvicorn.run(app, host=args.host, port=args.port, log_level="info")
2024-05-14 21:14:32 | ERROR | stderr |   File "/home/yyang/anaconda3/envs/matcha_new/lib/python3.9/site-packages/uvicorn/main.py", line 575, in run
2024-05-14 21:14:32 | ERROR | stderr |     server.run()
2024-05-14 21:14:32 | ERROR | stderr |   File "/home/yyang/anaconda3/envs/matcha_new/lib/python3.9/site-packages/uvicorn/server.py", line 65, in run
2024-05-14 21:14:32 | ERROR | stderr |     return asyncio.run(self.serve(sockets=sockets))
2024-05-14 21:14:32 | ERROR | stderr |   File "/home/yyang/anaconda3/envs/matcha_new/lib/python3.9/asyncio/runners.py", line 44, in run
2024-05-14 21:14:32 | ERROR | stderr |     return loop.run_until_complete(main)
2024-05-14 21:14:32 | ERROR | stderr |   File "uvloop/loop.pyx", line 1511, in uvloop.loop.Loop.run_until_complete
2024-05-14 21:14:32 | ERROR | stderr |   File "uvloop/loop.pyx", line 1504, in uvloop.loop.Loop.run_until_complete
2024-05-14 21:14:32 | ERROR | stderr |   File "uvloop/loop.pyx", line 1377, in uvloop.loop.Loop.run_forever
2024-05-14 21:14:32 | ERROR | stderr |   File "uvloop/loop.pyx", line 555, in uvloop.loop.Loop._run
2024-05-14 21:14:32 | ERROR | stderr |   File "uvloop/loop.pyx", line 474, in uvloop.loop.Loop._on_idle
2024-05-14 21:14:32 | ERROR | stderr |   File "uvloop/cbhandles.pyx", line 83, in uvloop.loop.Handle._run
2024-05-14 21:14:32 | ERROR | stderr |   File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
2024-05-14 21:14:32 | ERROR | stderr |   File "/home/yyang/anaconda3/envs/matcha_new/lib/python3.9/site-packages/uvicorn/server.py", line 69, in serve
2024-05-14 21:14:32 | ERROR | stderr |     await self._serve(sockets)
2024-05-14 21:14:32 | ERROR | stderr |   File "/home/yyang/anaconda3/envs/matcha_new/lib/python3.9/contextlib.py", line 124, in __exit__
2024-05-14 21:14:32 | ERROR | stderr |     next(self.gen)
2024-05-14 21:14:32 | ERROR | stderr |   File "/home/yyang/anaconda3/envs/matcha_new/lib/python3.9/site-packages/uvicorn/server.py", line 328, in capture_signals
2024-05-14 21:14:32 | ERROR | stderr |     signal.raise_signal(captured_signal)
2024-05-14 21:14:32 | ERROR | stderr | KeyboardInterrupt
2024-05-14 21:14:35 | ERROR | stderr | Exception ignored in: <module 'threading' from '/home/yyang/anaconda3/envs/matcha_new/lib/python3.9/threading.py'>
2024-05-14 21:14:35 | ERROR | stderr | Traceback (most recent call last):
2024-05-14 21:14:35 | ERROR | stderr |   File "/home/yyang/anaconda3/envs/matcha_new/lib/python3.9/threading.py", line 1424, in _shutdown
2024-05-14 21:14:35 | ERROR | stderr |     lock.acquire()
2024-05-14 21:14:35 | ERROR | stderr | KeyboardInterrupt:
2024-05-14 21:14:48 | INFO | controller | args: Namespace(host='localhost', port=21001, dispatch_method='shortest_queue', ssl=False)
2024-05-14 21:14:48 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m67790[0m]
2024-05-14 21:14:48 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2024-05-14 21:14:48 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2024-05-14 21:14:48 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://localhost:21001[0m (Press CTRL+C to quit)
2024-05-14 21:46:09 | ERROR | stderr | [32mINFO[0m:     Shutting down
2024-05-14 21:46:09 | ERROR | stderr | [32mINFO[0m:     Waiting for application shutdown.
2024-05-14 21:46:09 | ERROR | stderr | [32mINFO[0m:     Application shutdown complete.
2024-05-14 21:46:09 | ERROR | stderr | [32mINFO[0m:     Finished server process [[36m67790[0m]
2024-05-14 21:46:09 | ERROR | stderr | Traceback (most recent call last):
2024-05-14 21:46:09 | ERROR | stderr |   File "/home/yyang/anaconda3/envs/matcha_new/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2024-05-14 21:46:09 | ERROR | stderr |     return _run_code(code, main_globals, None,
2024-05-14 21:46:09 | ERROR | stderr |   File "/home/yyang/anaconda3/envs/matcha_new/lib/python3.9/runpy.py", line 87, in _run_code
2024-05-14 21:46:09 | ERROR | stderr |     exec(code, run_globals)
2024-05-14 21:46:09 | ERROR | stderr |   File "/home/yyang/anaconda3/envs/matcha_new/lib/python3.9/site-packages/fastchat/serve/controller.py", line 389, in <module>
2024-05-14 21:46:09 | ERROR | stderr |     uvicorn.run(app, host=args.host, port=args.port, log_level="info")
2024-05-14 21:46:09 | ERROR | stderr |   File "/home/yyang/anaconda3/envs/matcha_new/lib/python3.9/site-packages/uvicorn/main.py", line 575, in run
2024-05-14 21:46:09 | ERROR | stderr |     server.run()
2024-05-14 21:46:09 | ERROR | stderr |   File "/home/yyang/anaconda3/envs/matcha_new/lib/python3.9/site-packages/uvicorn/server.py", line 65, in run
2024-05-14 21:46:09 | ERROR | stderr |     return asyncio.run(self.serve(sockets=sockets))
2024-05-14 21:46:09 | ERROR | stderr |   File "/home/yyang/anaconda3/envs/matcha_new/lib/python3.9/asyncio/runners.py", line 44, in run
2024-05-14 21:46:09 | ERROR | stderr |     return loop.run_until_complete(main)
2024-05-14 21:46:09 | ERROR | stderr |   File "uvloop/loop.pyx", line 1511, in uvloop.loop.Loop.run_until_complete
2024-05-14 21:46:09 | ERROR | stderr |   File "uvloop/loop.pyx", line 1504, in uvloop.loop.Loop.run_until_complete
2024-05-14 21:46:09 | ERROR | stderr |   File "uvloop/loop.pyx", line 1377, in uvloop.loop.Loop.run_forever
2024-05-14 21:46:09 | ERROR | stderr |   File "uvloop/loop.pyx", line 555, in uvloop.loop.Loop._run
2024-05-14 21:46:09 | ERROR | stderr |   File "uvloop/loop.pyx", line 474, in uvloop.loop.Loop._on_idle
2024-05-14 21:46:09 | ERROR | stderr |   File "uvloop/cbhandles.pyx", line 83, in uvloop.loop.Handle._run
2024-05-14 21:46:09 | ERROR | stderr |   File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
2024-05-14 21:46:09 | ERROR | stderr |   File "/home/yyang/anaconda3/envs/matcha_new/lib/python3.9/site-packages/uvicorn/server.py", line 69, in serve
2024-05-14 21:46:09 | ERROR | stderr |     await self._serve(sockets)
2024-05-14 21:46:09 | ERROR | stderr |   File "/home/yyang/anaconda3/envs/matcha_new/lib/python3.9/contextlib.py", line 124, in __exit__
2024-05-14 21:46:09 | ERROR | stderr |     next(self.gen)
2024-05-14 21:46:09 | ERROR | stderr |   File "/home/yyang/anaconda3/envs/matcha_new/lib/python3.9/site-packages/uvicorn/server.py", line 328, in capture_signals
2024-05-14 21:46:09 | ERROR | stderr |     signal.raise_signal(captured_signal)
2024-05-14 21:46:09 | ERROR | stderr | KeyboardInterrupt
2024-05-14 21:46:09 | ERROR | stderr | Exception ignored in: <module 'threading' from '/home/yyang/anaconda3/envs/matcha_new/lib/python3.9/threading.py'>
2024-05-14 21:46:09 | ERROR | stderr | Traceback (most recent call last):
2024-05-14 21:46:09 | ERROR | stderr |   File "/home/yyang/anaconda3/envs/matcha_new/lib/python3.9/threading.py", line 1424, in _shutdown
2024-05-14 21:46:09 | ERROR | stderr |     lock.acquire()
2024-05-14 21:46:09 | ERROR | stderr | KeyboardInterrupt:
